services:
  db:
    image: pgvector/pgvector:pg17
    environment:
      POSTGRES_PASSWORD: motdepasse
      POSTGRES_DB: banking_compliance_db
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://postgres:motdepasse@db:5432/banking_compliance_db
    depends_on:
      - db

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend

volumes:
  db_data: